#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
127_pam_keyring_greetd.py — Platinum v3.1 (Python 3.14.6 / Hyprland 0.55.4+ native)
Arch Linux: Greetd + tuigreet + GNOME Keyring SSO + udiskie + pure Hyprland

What changed from bash v2:
  - UWSM removed completely (Hyprland no longer recommends it, start-hyprland is official)【6711999833282738214†L337-L344】
  - /usr/local/bin/wayland-session now = exec start-hyprland (crash-recovery wrapper)【737277359055782423†L43-L46】
  - greetd config uses [terminal] vt=1 + [default_session] + optional [initial_session]【5602483336053642662†L13-L18】
  - PAM: auth optional pam_gnome_keyring.so + session optional ... auto_start in /etc/pam.d/greetd AND /etc/pam.d/login【506230610187225611†L25-L31】【2792915181519492705†L80-L96】
  - tuigreet cache handling  /var/cache/tuigreet chown greeter:greeter 0755【361548926156822557†L66-L70】
  - systemd override KeyringMode=inherit for kernel keyring inheritance【361548926156822557†L5-L12】
  - Masks gnome-keyring-daemon.service/socket globally to avoid duplicate daemon race (Hyprland syncs env via dbus-update-activation-environment)

Reliability features:
  - Auto-elevates via sudo with password prompt
  - Auto-installs missing Python libs via pacman (python-rich, python-tomlkit, python-psutil)
  - Auto-installs system deps via pacman (greetd, tuigreet, etc.)
  - Atomic writes (tmpfile + fsync + os.replace) for every system file
  - Regex-idempotent PAM editing, backups with retention
  - JSON-based lsblk/findmnt parsing with fallback
  - Rich Progress, Panels, Tree, Syntax preview, final verification table
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# 0. Minimal bootstrap — no rich yet, install it if missing, then re-exec
# ---------------------------------------------------------------------------
import sys, os, subprocess, importlib

PY_DEPS: dict[str, str] = {
    "rich": "python-rich",
    "tomlkit": "python-tomlkit",
    "psutil": "python-psutil",
}

def _bootstrap_py_deps() -> None:
    missing_pacman: list[str] = []
    for mod, pkg in PY_DEPS.items():
        try:
            importlib.import_module(mod)
        except ImportError:
            missing_pacman.append(pkg)
    if missing_pacman:
        if os.geteuid() != 0:
            print("[bootstrap] Root required to install missing Python dependencies. Escalating via sudo...")
            try:
                os.execvp("sudo", ["sudo", "-p", "[sudo] password for %u: ", sys.executable] + sys.argv)
            except FileNotFoundError:
                print("[bootstrap] sudo not found. Please run as root.")
                sys.exit(1)
        print(f"[bootstrap] Installing missing Python deps: {' '.join(missing_pacman)}")
        try:
            subprocess.check_call(["pacman", "-S", "--needed", "--noconfirm"] + missing_pacman)
        except Exception as e:
            print(f"[bootstrap] pacman failed: {e} — trying pip fallback")
            # fallback pip (last resort, Arch prefers pacman)
            pip_pkgs = [m for m in missing_pacman]  # same names mostly work
            subprocess.check_call([sys.executable, "-m", "pip", "install", "--break-system-packages"] + [k for k in PY_DEPS.keys() if k not in sys.modules])
        # re-exec to load newly installed modules
        os.execv(sys.executable, [sys.executable] + sys.argv)

_bootstrap_py_deps()

# Now safe to import rich and friends
import argparse
import json
import re
import shutil
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
import pwd

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.tree import Tree
from rich.syntax import Syntax
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
from rich.prompt import Confirm
from rich import box
from rich.rule import Rule
import tomlkit  # type: ignore
import psutil  # type: ignore

console = Console()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SYSTEM_PKGS = ["greetd", "greetd-tuigreet", "udiskie", "libsecret", "gnome-keyring"]
WAYLAND_SESSION = Path("/usr/local/bin/wayland-session")
GREETD_CFG = Path("/etc/greetd/config.toml")
PAM_GREETD = Path("/etc/pam.d/greetd")
PAM_LOGIN = Path("/etc/pam.d/login")
OVERRIDE_CONF = Path("/etc/systemd/system/greetd.service.d/keyringmode.conf")
TUIGREET_CACHE = Path("/var/cache/tuigreet")

WAYLAND_SESSION_SRC = """#!/usr/bin/env bash
# Generated by 127_pam_keyring_greetd.py — Platinum v3.1
# Pure Hyprland 0.55.4+ native session (no UWSM)
# start-hyprland provides crash recovery + safe mode per upstream
set -euo pipefail
exec start-hyprland
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def run(cmd: list[str], check: bool = True, **kw) -> subprocess.CompletedProcess:
    console.log(f"[dim]$ {' '.join(cmd)}[/dim]")
    return subprocess.run(cmd, check=check, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kw)

def ensure_root_or_escalate() -> None:
    if os.geteuid() == 0:
        return
    console.print(Panel("Root required — escalating via sudo (you will be prompted)", style="yellow"))
    # Use sudo to re-run same interpreter + script + args
    # -p gives nice prompt, -E preserves some env if needed
    try:
        os.execvp("sudo", ["sudo", "-p", "[sudo] password for %u: ", sys.executable] + sys.argv)
    except FileNotFoundError:
        console.print("[red]sudo not found. Please run as root.[/red]")
        sys.exit(1)

def get_real_user() -> tuple[str, Path]:
    sudo_user = os.environ.get("SUDO_USER")
    if sudo_user and sudo_user != "root":
        try:
            pw = pwd.getpwnam(sudo_user)
            return sudo_user, Path(pw.pw_dir)
        except KeyError:
            pass
    # fallback: first regular UID 1000-59999
    for pw in pwd.getpwall():
        if 1000 <= pw.pw_uid < 60000 and pw.pw_name not in ("nobody", "greeter"):
            return pw.pw_name, Path(pw.pw_dir)
    console.print("[red]Cannot determine real user (no UID 1000+ found)[/red]")
    sys.exit(1)

def is_root_encrypted() -> bool:
    """Robust LUKS detection via findmnt -J + lsblk -J, fallback to text parsing."""
    try:
        j = json.loads(subprocess.check_output(["findmnt", "-J", "-n", "-o", "SOURCE", "/"], text=True))
        src = j["filesystems"][0]["source"]
        raw = src.split("[")[0]
        blk = json.loads(subprocess.check_output(["lsblk", "-J", "-s", "-o", "TYPE,NAME", raw], text=True))
        # walk devices
        def has_crypt(devs):
            for d in devs:
                if d.get("type") == "crypt":
                    return True
                if "children" in d and has_crypt(d["children"]):
                    return True
            return False
        return has_crypt(blk.get("blockdevices", []))
    except Exception:
        # fallback classic
        try:
            src = subprocess.check_output(["findmnt", "-n", "-o", "SOURCE", "/"], text=True).strip().split("[")[0]
            out = subprocess.check_output(["lsblk", "-s", "-no", "TYPE", src], text=True)
            return "crypt" in out
        except Exception:
            return False

def atomic_write(target: Path, content: str | bytes, mode: int = 0o644, owner: str | None = None) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    is_bytes = isinstance(content, bytes)
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), prefix=f".{target.name}.tmp.")
    try:
        if is_bytes:
            with os.fdopen(fd, "wb") as f:
                f.write(content)  # type: ignore
                f.flush(); os.fsync(f.fileno())
        else:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(content)
                f.flush(); os.fsync(f.fileno())
        os.chmod(tmp, mode)
        if owner:
            try:
                shutil.chown(tmp, user=owner, group=owner)
            except Exception:
                pass
        os.replace(tmp, target)
    finally:
        Path(tmp).unlink(missing_ok=True)

def backup_with_retention(p: Path, keep: int = 3) -> None:
    if not p.exists():
        return
    bak = p.with_name(f"{p.name}.bak.{int(time.time())}")
    shutil.copy2(p, bak)
    # prune old backups
    backs = sorted(p.parent.glob(f"{p.name}.bak.*"), key=lambda x: x.stat().st_mtime, reverse=True)
    for old in backs[keep:]:
        try:
            old.unlink()
        except Exception:
            pass

def pacman_is_installed(pkg: str) -> bool:
    return subprocess.run(["pacman", "-Qq", pkg], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0

# ---------------------------------------------------------------------------
# Core Deployer
# ---------------------------------------------------------------------------
@dataclass(slots=True)
class Deployer:
    real_user: str
    home: Path
    mode_arg: str
    active_mode: str = ""
    dry_run: bool = False

    def resolve_mode(self) -> None:
        console.rule("[bold cyan]Stage 1 — Topology & Mode Resolution")
        enc = is_root_encrypted()
        console.print(f"Root encrypted (LUKS): [bold]{enc}[/bold]")
        if self.mode_arg == "auto":
            self.active_mode = "luks" if enc else "unencrypted"
            console.print(f"Auto → [green]{self.active_mode}[/green]")
        else:
            m = "luks" if self.mode_arg == "encrypted" else self.mode_arg
            if m == "luks" and not enc:
                console.print("[red]FATAL: --mode luks on unencrypted root[/red]")
                sys.exit(1)
            self.active_mode = m
            console.print(f"Forced → [yellow]{self.active_mode}[/yellow]")

    def install_system_deps(self) -> None:
        console.rule("[bold cyan]Stage 2 — System Dependencies")
        to_install = [p for p in SYSTEM_PKGS if not pacman_is_installed(p)]
        if not to_install:
            console.print("[green]All base packages already installed[/green]")
            return
        console.print(f"Missing: {', '.join(to_install)}")
        if self.dry_run:
            console.print("[dim]dry-run: would run pacman -S[/dim]")
            return
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), BarColumn(), TaskProgressColumn(), console=console) as prog:
            t = prog.add_task(f"Installing {len(to_install)} packages", total=len(to_install))
            # pacman installs atomically in one call, but we fake progress
            try:
                run(["pacman", "-S", "--needed", "--noconfirm"] + to_install, check=True)
                prog.update(t, completed=len(to_install))
            except subprocess.CalledProcessError as e:
                console.print(f"[red]pacman failed:[/red]\n{e.stdout}")
                sys.exit(1)

    def deploy_session_wrapper(self) -> None:
        console.rule("[bold cyan]Stage 3 — Native Wayland Session Wrapper")
        if self.dry_run:
            console.print(Syntax(WAYLAND_SESSION_SRC, "bash", theme="monokai", line_numbers=True))
            return
        backup_with_retention(WAYLAND_SESSION)
        atomic_write(WAYLAND_SESSION, WAYLAND_SESSION_SRC, mode=0o755)
        console.print(f"[green]✔[/green] {WAYLAND_SESSION} [dim](0755, exec start-hyprland)[/dim]")
        console.print(Syntax(WAYLAND_SESSION_SRC, "bash", theme="monokai"))

    def setup_tuigreet(self) -> None:
        console.rule("[bold cyan]Stage 4a — tuigreet Cache")
        if self.dry_run:
            return
        TUIGREET_CACHE.mkdir(parents=True, exist_ok=True)
        os.chmod(TUIGREET_CACHE, 0o755)
        try:
            shutil.chown(TUIGREET_CACHE, user="greeter", group="greeter")
            console.print(f"[green]✔[/green] {TUIGREET_CACHE} → greeter:greeter 0755")
        except Exception:
            console.print(f"[yellow]![/yellow] greeter user not yet present, will be fixed after greetd install")

    def write_greetd_config(self) -> None:
        console.rule(f"[bold cyan]Stage 4b — /etc/greetd/config.toml [{self.active_mode}]")
        doc = tomlkit.document()
        term = tomlkit.table(); term["vt"] = 1
        doc["terminal"] = term
        default = tomlkit.table()
        default["command"] = "tuigreet --time --remember --remember-session --cmd /usr/local/bin/wayland-session"
        default["user"] = "greeter"
        doc["default_session"] = default
        if self.active_mode != "unencrypted":
            init = tomlkit.table()
            init["command"] = "/usr/local/bin/wayland-session"
            init["user"] = self.real_user
            doc["initial_session"] = init
            console.print("[yellow]Autologin enabled via [initial_session] (encrypted/luks/autologin)[/yellow]")
        else:
            console.print("[green]Standard password prompt via [default_session] only[/green]")

        rendered = tomlkit.dumps(doc)
        if self.dry_run:
            console.print(Syntax(rendered, "toml", theme="monokai"))
            return
        backup_with_retention(GREETD_CFG)
        atomic_write(GREETD_CFG, rendered, mode=0o644)
        try:
            shutil.chown(GREETD_CFG.parent, user="greeter", group="greeter")
            shutil.chown(GREETD_CFG, user="greeter", group="greeter")
        except Exception:
            pass
        console.print(Syntax(rendered, "toml", theme="monokai", line_numbers=True))

    def ensure_pam(self, path: Path) -> None:
        console.print(f"→ Checking {path}")
        if not path.exists():
            atomic_write(path, "#%PAM-1.0\n", mode=0o644)
        text = path.read_text(encoding="utf-8", errors="ignore")
        has_auth = bool(re.search(r'^\s*auth\s+.*\bpam_gnome_keyring\.so\b', text, re.M))
        has_sess = bool(re.search(r'^\s*session\s+.*\bpam_gnome_keyring\.so\b.*\bauto_start\b', text, re.M))
        if has_auth and has_sess:
            console.print(f"  [dim]already ok[/dim]")
            return
        # insert after last auth / session include
        lines = text.splitlines()
        def insert_after(last_pat: str, new_line: str):
            idx = -1
            for i, l in enumerate(lines):
                if re.match(last_pat, l):
                    idx = i
            if idx >= 0:
                lines.insert(idx+1, new_line)
            else:
                lines.append(new_line)
        if not has_auth:
            insert_after(r'^\s*auth\s+', "auth       optional     pam_gnome_keyring.so")
        if not has_sess:
            insert_after(r'^\s*session\s+', "session    optional     pam_gnome_keyring.so auto_start")
        if self.dry_run:
            console.print(Syntax("\n".join(lines), "ini"))
            return
        backup_with_retention(path)
        atomic_write(path, "\n".join(lines)+"\n", mode=0o644)
        console.print(f"  [green]✔ patched[/green]")

    def setup_pam_stack(self) -> None:
        console.rule("[bold cyan]Stage 5 — PAM Stack (gnome-keyring autounlock)")
        for p in (PAM_GREETD, PAM_LOGIN):
            self.ensure_pam(p)

    def setup_systemd(self) -> None:
        console.rule("[bold cyan]Stage 6 — systemd Overrides & Masking")
        if self.dry_run:
            console.print(f"would write {OVERRIDE_CONF} with KeyringMode=inherit")
            return
        atomic_write(OVERRIDE_CONF, "[Service]\nKeyringMode=inherit\n", mode=0o644)
        console.print(f"[green]✔[/green] {OVERRIDE_CONF}")
        # global mask to avoid duplicate daemon race — Hyprland native syncs env itself
        run(["systemctl", "--global", "mask", "gnome-keyring-daemon.service", "gnome-keyring-daemon.socket"], check=False)
        for unit in ("gnome-keyring-daemon.service", "gnome-keyring-daemon.socket"):
            link = Path(f"/etc/systemd/user/{unit}")
            try:
                link.parent.mkdir(parents=True, exist_ok=True)
                if link.exists() or link.is_symlink():
                    link.unlink()
                link.symlink_to("/dev/null")
            except Exception as e:
                console.log(f"mask symlink fallback {unit}: {e}")
        console.print("[green]✔[/green] gnome-keyring units masked globally → PAM-started daemon wins")

    def setup_udiskie(self) -> None:
        console.rule("[bold cyan]Stage 7 — udiskie (secret-tool integration)")
        cfg_dir = self.home / ".config" / "udiskie"
        cfg = cfg_dir / "config.yml"
        yml = """program_options:
  password_prompt: ["secret-tool", "lookup", "uuid", "{id_uuid}"]
  automount: true
  notify: true
  tray: auto
"""
        if self.dry_run:
            console.print(Syntax(yml, "yaml", theme="monokai"))
            return
        cfg_dir.mkdir(parents=True, exist_ok=True)
        atomic_write(cfg, yml, mode=0o644, owner=self.real_user)
        try:
            shutil.chown(cfg_dir, user=self.real_user, group=self.real_user)
        except Exception:
            pass
        console.print(f"[green]✔[/green] {cfg}")

    def enable_services(self) -> None:
        console.rule("[bold cyan]Stage 8 — Enable greetd.service")
        if self.dry_run:
            return
        # psutil can also detect container/chroot, but use systemd-detect-virt for canonical
        is_chroot = subprocess.run(["systemd-detect-virt", "-q", "--chroot"]).returncode == 0
        if is_chroot:
            run(["systemctl", "enable", "greetd.service", "--force"], check=False)
        else:
            run(["systemctl", "daemon-reload"], check=False)
            run(["systemctl", "enable", "greetd.service"], check=False)

    def verify(self) -> None:
        console.rule("[bold green]Verification")
        tree = Tree("[bold]Deployment Tree[/bold]")
        tree.add(f"[green]{WAYLAND_SESSION}[/green] → exec start-hyprland")
        tree.add(f"[green]{GREETD_CFG}[/green] ({self.active_mode})")
        tree.add(f"{PAM_GREETD} + {PAM_LOGIN} [green]patched[/green]")
        tree.add(f"{OVERRIDE_CONF} [green]KeyringMode=inherit[/green]")
        tree.add(f"{TUIGREET_CACHE} [green]0755[/green]")
        console.print(tree)
        tbl = Table(title="Final State", box=box.ROUNDED)
        tbl.add_column("Check", style="cyan"); tbl.add_column("Result", style="white")
        for bin_name in ("greetd", "tuigreet", "Hyprland", "secret-tool"):
            found = shutil.which(bin_name) is not None
            tbl.add_row(bin_name, "[green]found[/green]" if found else "[red]missing[/red]")
        tbl.add_row("Mode", self.active_mode.upper())
        tbl.add_row("UWSM", "[dim]removed[/dim]")
        tbl.add_row("Keyring Mask", "masked --global")
        console.print(tbl)
        if self.active_mode == "autologin":
            console.print(Panel("[yellow]autologin on unencrypted drive → keyring will start LOCKED unless you set blank keyring password or use same password as user[/yellow]", title="WARNING", style="red"))


def parse_args():
    p = argparse.ArgumentParser(description="Platinum Wayland SSO — Hyprland 0.55.4+ native (Python 3.14.6)")
    p.add_argument("-m","--mode", default="auto", choices=["auto","unencrypted","luks","autologin","encrypted"], help="auto=detect LUKS, unencrypted=force prompt, luks/encrypted/autologin=autologin via initial_session")
    p.add_argument("--dry-run", action="store_true", help="Show what would be done, no writes")
    p.add_argument("--yes", action="store_true", help="Non-interactive, skip confirmations")
    return p.parse_args()

def main():
    args = parse_args()
    ensure_root_or_escalate()
    real_user, home = get_real_user()
    console.print(Panel(f"[bold]Target:[/bold] {real_user}  [dim]{home}[/dim]  |  [bold]Python:[/bold] {sys.version.split()[0]}  |  [bold]PID:[/bold] {os.getpid()}", title="Platinum Deployer v3.1", style="magenta"))

    mode = args.mode
    deployer = Deployer(real_user=real_user, home=home, mode_arg=mode, dry_run=args.dry_run)

    if not args.yes and not args.dry_run and mode in ("autologin", "luks", "encrypted"):
        if not Confirm.ask(f"[yellow]Enable autologin for {real_user}? Keyring may stay locked unless password matches. Continue?[/yellow]", default=True):
            console.print("[red]Aborted[/red]"); sys.exit(0)

    deployer.resolve_mode()
    deployer.install_system_deps()
    deployer.deploy_session_wrapper()
    deployer.setup_tuigreet()
    deployer.write_greetd_config()
    deployer.setup_pam_stack()
    deployer.setup_systemd()
    deployer.setup_udiskie()
    deployer.enable_services()
    deployer.verify()
    console.print(Rule("[bold green]Done — reboot to test greetd → tuigreet → start-hyprland[/bold green]"))

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[red]Interrupted[/red]"); sys.exit(130)
    except Exception as e:
        console.print_exception(show_locals=True)
        sys.exit(1)
