#!/usr/bin/env bash
# ==============================================================================
# 130_kvm_vfio_isolation.sh
# Purpose: Dynamic GPU Passthrough Isolation. Configures Limine/systemd-boot,
#          mkinitcpio drop-ins, and softdeps to steal the GPU before the host OS.
# ==============================================================================
set -euo pipefail

CYAN='\033[1;36m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

log_info() { echo -e "${CYAN}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo -e "${CYAN}====================================================${NC}"
echo -e "${CYAN}          GPU VFIO Isolation Configuration          ${NC}"
echo -e "${CYAN}====================================================${NC}"

read -rp "Do you want to configure GPU Passthrough (VFIO Isolation)? [y/N]: " ISOLATE_CHOICE
if [[ ! "$ISOLATE_CHOICE" =~ ^[Yy]$ ]]; then
    log_info "Skipping GPU isolation."
    exit 0
fi

log_warn "MUX Switch laptops MUST have BIOS set to Hybrid/iGPU mode to prevent black screens."

# Hardware Intelligence: CPU IOMMU Detection
if grep -q -i "intel" /proc/cpuinfo; then
    IOMMU_PARAM="intel_iommu=on iommu=pt"
    log_info "Detected Intel CPU. Using: $IOMMU_PARAM"
elif grep -q -i "amd" /proc/cpuinfo; then
    IOMMU_PARAM="amd_iommu=on iommu=pt"
    log_info "Detected AMD CPU. Using: $IOMMU_PARAM"
else
    IOMMU_PARAM="iommu=pt"
    log_warn "Could not explicitly determine CPU vendor. Defaulting to: $IOMMU_PARAM"
fi

log_info "Available PCIe Display/VGA devices:"
lspci -nn | grep -iE 'vga|3d|display|audio' | grep -i nvidia || true

echo ""
read -rp "Enter the Vendor:Product ID of the GPU to isolate (e.g., 10de:25a0): " GPU_ID
read -rp "Enter the Vendor:Product ID of its Audio Controller (e.g., 10de:2291): " AUDIO_ID

if [[ -z "$GPU_ID" || -z "$AUDIO_ID" ]]; then
    log_error "Both GPU and Audio IDs are required for correct IOMMU grouping. Aborting."
fi

VFIO_PARAMS="${IOMMU_PARAM} vfio-pci.ids=${GPU_ID},${AUDIO_ID} module_blacklist=nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm,nouveau"

# Modprobe Safety Net
log_info "Configuring /etc/modprobe.d/vfio.conf..."
sudo tee /etc/modprobe.d/vfio.conf > /dev/null <<EOF
# Generated by Arch Orchestrator
options vfio-pci ids=${GPU_ID},${AUDIO_ID}
softdep nvidia pre: vfio-pci
softdep nouveau pre: vfio-pci
blacklist nouveau
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
EOF
log_success "Modprobe rules applied."

# Mkinitcpio Modern Drop-in
log_info "Deploying mkinitcpio drop-in..."
sudo mkdir -p /etc/mkinitcpio.conf.d
sudo tee /etc/mkinitcpio.conf.d/15-vfio.conf > /dev/null <<EOF
# VFIO Modules for GPU Passthrough - Generated by Arch Orchestrator
MODULES=(vfio_pci vfio vfio_iommu_type1)
EOF
sudo chmod 0644 /etc/mkinitcpio.conf.d/15-vfio.conf
log_success "Drop-in /etc/mkinitcpio.conf.d/15-vfio.conf created."

# Bootloader Injection
log_info "Injecting kernel parameters into bootloader..."

if [[ -f "/etc/kernel/cmdline" ]]; then
    log_info "Detected Limine bootloader (/etc/kernel/cmdline)."
    CURRENT_CMDLINE=$(< /etc/kernel/cmdline)
    
    if [[ "$CURRENT_CMDLINE" == *"${GPU_ID}"* ]]; then
        log_success "VFIO parameters already exist in Limine cmdline. Skipping injection to prevent duplication."
    else
        sudo cp /etc/kernel/cmdline /etc/kernel/cmdline.bak
        # Safely append params
        echo "${CURRENT_CMDLINE} ${VFIO_PARAMS}" | sudo awk '{$1=$1};1' | sudo tee /etc/kernel/cmdline > /dev/null
        log_success "Updated /etc/kernel/cmdline."
        
        if command -v limine-update >/dev/null 2>&1; then
            sudo limine-update
            log_success "Executed limine-update."
        fi
    fi

elif [[ -d "/boot/loader/entries" ]]; then
    log_info "Detected systemd-boot."
    for conf in /boot/loader/entries/*.conf; do
        if grep -q "^options" "$conf"; then
            if grep -q "${GPU_ID}" "$conf"; then
                log_success "VFIO parameters already exist in $conf."
            else
                sudo sed -i "s/^options .*/& ${VFIO_PARAMS}/" "$conf"
                log_success "Updated $conf."
            fi
        fi
    done
    sudo bootctl update || true
else
    log_error "No supported bootloader config found."
fi

log_info "Regenerating initramfs to bake in VFIO modules..."
sudo mkinitcpio -P
log_success "Initramfs regeneration complete."

echo -e "${GREEN}=== GPU Isolation Complete ===${NC}"
echo -e "${YELLOW}Note: A system reboot is required for VFIO bindings to take effect.${NC}"
