-- DO NOT EDIT THIS FILE, if you want to configure something, edit the file 
-- at this location. ~/.config/hypr/edit_here/source/monitors.lua

-- #################################################################################################
-- SECTION 1: MONITOR CONFIGURATION
--
-- Guidelines:
-- - Rule Syntax: hl.monitor({ output = "NAME", mode = "RESOLUTION@REFRESH", position = "POSITION", scale = SCALE })
-- - "preferred" tells Hyprland to use the display's native resolution/refresh.
-- - "auto" lets Hyprland position the monitor automatically (usually to the right).
-- #################################################################################################

-- -------------------------------------------------------------------------------------------------
-- 1.1. FALLBACK / EXTERNAL MONITORS (CRITICAL)
-- -------------------------------------------------------------------------------------------------
-- This rule ensures that ANY external monitor/projector you plug in works instantly
-- at its native resolution with no scaling. Without this, hotplugged displays might remain black.
-- Leaving the output empty ("") creates the global fallback rule.
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto"
})

-- -------------------------------------------------------------------------------------------------
-- 1.2. WORKSPACE BINDING (Optional)
-- -------------------------------------------------------------------------------------------------
-- Useful if you want specific workspaces to always stay on the laptop screen.
-- Uncomment the block below to apply:
-- hl.config({
--     workspace = {
--         "1, monitor:eDP-1",
--         "2, monitor:eDP-1"
--     }
-- })

-- -------------------------------------------------------------------------------------------------
-- 1.3. Misc
-- -------------------------------------------------------------------------------------------------
hl.config({
    misc = {

--       for some reason vfr throws and error with unknown key 'misc.vfr on 55' so commented
        -- Power Saving & Refresh Rate (true saves power because gpu doesn't have to render frames when idle)
--         vfr = true,

        -- uses extra 1 watt but looks smoother when enabled (1)
        vrr = 0
    },

    debug = {

        -- Power Saving & Refresh Rate (true saves power because gpu doesn't have to render frames when idle)
        vfr = true
    }
})
