-- DO NOT EDIT THIS FILE, if you want to configure something, edit the file
-- at this location. ~/.config/hypr/edit_here/source/workspace_rules.lua

-- ------------------------------------------------------------------------------
-- IMMUTABLE BASE - Dusky TUI Variable-Proxy Engine
-- ------------------------------------------------------------------------------
-- NOTE: Standard workspace rules (1-10) and the global fallback (11-99) are 
-- strictly managed by the Dusky TUI Variable-Proxy Engine.
--
-- HYPRLAND 0.55+ ARCHITECTURE: 
-- Because the configuration is now fully Lua-based, the TUI does not need to 
-- generate raw config text. Instead, the TUI can populate the `tui_workspace_data` 
-- table below. The engine will loop through it programmatically.
-- ------------------------------------------------------------------------------

-- ==============================================================================
-- 1. TUI DATA INJECTION POINT
-- The TUI should generate and insert its rule tables here.
-- ==============================================================================
local tui_workspace_data = {
    -- Examples of what the TUI might generate based on user selection:
    
    -- [Monitor Binding & Persistence]
    -- { workspace = "1", monitor = "DP-1", default = true, persistent = true },
    -- { workspace = "2", monitor = "DP-1", persistent = true },
    -- { workspace = "3", monitor = "eDP-1", persistent = true },

    -- [Temporary / Project-Specific Workspaces]
    -- { workspace = "name:coding", monitor = "DP-1", gaps_in = 0, gaps_out = 0, no_border = true, no_rounding = true, decorate = false },
    
    -- [Special Workspaces / Scratchpads]
    -- { workspace = "special:scratchpad", on_created_empty = "kitty" },
    -- { workspace = "special:browser", on_created_empty = "firefox", layout = "scrolling" },

    -- [Aesthetic Overrides]
    -- { workspace = "8", border_size = 8, animation = "slidevert", default_name = "visuals" }
}

-- Engine Loop: Applies all generated TUI rules to Hyprland
for _, rule in ipairs(tui_workspace_data) do
    hl.workspace_rule(rule)
end


-- ==============================================================================
-- 2. DYNAMIC WORKSPACE GENERATOR (1-10)
-- Instead of hardcoding 10 lines, the TUI can toggle a loop.
-- Example: Make workspaces 1 through 10 persistent globally.
-- ==============================================================================
local enforce_persistent_1_to_10 = false

if enforce_persistent_1_to_10 then
    for i = 1, 10 do
        hl.workspace_rule({
            workspace = tostring(i),
            persistent = true
        })
    end
end


-- ==============================================================================
-- 3. SMART GAPS MODULE (No Gaps When Only)
-- This replicates the popular "smart gaps" feature. It removes gaps and borders 
-- when there is only one tiled window on a screen, or when the window is fullscreen.
-- 
-- Selectors utilized:
-- w[tv1] : Workspace has exactly 1 visible tiled window
-- f[1]   : Fullscreen state of the workspace is maximized
-- s[false] : Ignores special workspaces
-- ==============================================================================
local enable_smart_gaps = false

if enable_smart_gaps then
    -- Workspace Rules: Remove gaps
    hl.workspace_rule({ workspace = "w[tv1]s[false]", gaps_out = 0, gaps_in = 0 })
    hl.workspace_rule({ workspace = "f[1]s[false]", gaps_out = 0, gaps_in = 0 })

    -- Window Rules: Remove borders and rounding for those specific states
    hl.window_rule({ match = { float = false, workspace = "w[tv1]s[false]" }, border_size = 0, rounding = 0 })
    hl.window_rule({ match = { float = false, workspace = "f[1]s[false]" }, border_size = 0, rounding = 0 })
end


-- ==============================================================================
-- 4. RANGE RULES (Global Fallbacks)
-- The TUI can apply broad rules across ranges of workspaces.
-- ==============================================================================
local enforce_global_fallbacks = false

if enforce_global_fallbacks then
    -- Example: Workspaces 11 through 99 use the "scrolling" layout by default
    hl.workspace_rule({
        workspace = "r[11-99]",
        layout = "scrolling"
    })
end


-- ==============================================================================
-- 5. preserve_split needs to be true for toggle split keybind to work
-- ==============================================================================

hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})


